language: go

go:
  - "1.10"
  - "1.11"
  - tip

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - go get github.com/golang/dep/...
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/goveralls

install:
  - $GOPATH/bin/dep ensure

script:
  - make test
  - make lint

after_script: |
  if [[ $TRAVIS_GO_VERSION == 1.11* ]] && [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    goveralls -repotoken ${COVERALLS_TOKEN}
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    docker build -t ike-dai/wego:latest .
    docker push ike-dai/wego:latest
  fi
